project:
  type: website

website:
  cookie-consent: true
  bread-crumbs: true
  title: "Lorenzo Mattioli"
  navbar:
    right:
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/lorMatt
      - icon: instagram
        href: https://www.instagram.com/ermattaraus/
format:
  html:
    theme: litera
    css: styles.css

editor: visual

